-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 13:55:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prueba` (
  `idprueba` INT NOT NULL,
  PRIMARY KEY (`idprueba`))
ENGINE = InnoDB;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`cliente` (
  `idCliente` INT(11) NOT NULL,
  `Nombre_cliente` VARCHAR(45) NOT NULL,
  `Dirección_postal` VARCHAR(80) NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `Correo_electronico` VARCHAR(60) NOT NULL,
  `Fecha_Registro` DATETIME NOT NULL,
  `clienteReferido` INT(11) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Correo_electronico` (`Correo_electronico` ASC),
  INDEX `Cliente_recomendador_id` (`clienteReferido` ASC),
  CONSTRAINT `fk_idCliente`
    FOREIGN KEY (`clienteReferido`)
    REFERENCES `optica`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optica`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedores` (
  `id_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `Fax` INT(11) NULL DEFAULT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Calle` VARCHAR(50) NOT NULL,
  `Numero` INT(11) NOT NULL,
  `Piso` INT(11) NULL DEFAULT NULL,
  `Puerta` INT(11) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(50) NOT NULL,
  `Codigo_postal` INT(11) NOT NULL,
  `Pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `NIF` (`NIF` ASC),
  UNIQUE INDEX `Codigo_postal` (`Codigo_postal` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`gafas` (
  `id_gafas` INT(11) NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NOT NULL,
  `id_proveedor` INT(11) NOT NULL,
  `Graduacion_derecho` INT(11) NOT NULL,
  `Graduacion_izqdo` INT(11) NOT NULL,
  `Tipo_montura` VARCHAR(20) NOT NULL,
  `Color_montura` VARCHAR(20) NOT NULL,
  `Color_cristal_derecho` VARCHAR(20) NULL DEFAULT NULL,
  `Color_cristal_izqdo` VARCHAR(20) NULL DEFAULT NULL,
  `Precio_gafas` INT(11) NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `gafas_ibfk_1_idx` (`id_proveedor` ASC),
  CONSTRAINT `gafas_ibfk_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `optica`.`proveedores` (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optica`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`vendedor` (
  `id_vendedor` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_vendedor` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`venta` (
  `id_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_vendedor` INT(11) NOT NULL,
  `id_gafas` INT(11) NOT NULL,
  `IdCliente` INT(11) NOT NULL,
  `Nombre_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `id_vendedor` (`id_vendedor` ASC),
  INDEX `id_gafas` (`id_gafas` ASC),
  INDEX `IdCliente` (`IdCliente` ASC),
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `optica`.`vendedor` (`id_vendedor`),
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`id_gafas`)
    REFERENCES `optica`.`gafas` (`id_gafas`),
  CONSTRAINT `venta_ibfk_3`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `optica`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
